:banner
	mode con: cols=90 lines=20

cls
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL     LLLLLLLLLLLLLLLLLLLLLLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL                         LLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL                         LLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL       LLLLL
echo LLLLL       LLLL    LLLLLL       LL         LLL       LLLLLLLLLL       LLLLLLL       LLLLL
echo LLLLL       LLLL    LLLLLL       LL         LLLL       LLLLLLLL       LLLLLLLL       LLLLL
echo LLLLL       LLLL    LLLLLL       LLLLLLLLLLLLLLLL       LLLLLL       LLLLLLLLLLLLLLLLLLLLL
echo LLLLL       LLLL    LLLLLL       LL       LLLLLLLL       LLLL       LLL       LLLLLLLLLLLL
echo LLLLL       LLLL    LLLLLL       LL       LLLLLLLLL       LL       LLLL       LLLLLLLLLLLL
echo LLLLL       LLLL    LLLLLL       LL       LLLLLLLLLL              LLLLL       LLLLLLLLLLLL
echo LLLLL       LLLLLLLLLLLLLL       LLLLLLLLLLLLLLLLLLLL            LLLLLL       LLLLLLLLLLLL
echo LLLLL                  LLL       LL         LLLLLLLLLL          LLLLLLL       LLLLLLLLLLLL
echo LLLLL                  LLL       LL         LLLLLLLLLLL        LLLLLLLL       LLLLLLLLLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLL    LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL    LLLL    LLLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLL    LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL    LLLL    LLLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
echo LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

	timeout /t 1 >nul


:contato
	mode con: cols=100 lines=10

	cls
	echo.
echo 	Pack de correções Windows FG204, 2nd Edition Ver 2.31 [16.07.2023]
echo 	Este script aplica correções para a maioria dos problemas conhecidos nas versões do
echo 	Windows 7, 8, 8.1, 10 e 11
echo 	NÃO. Isso não vai danificar nada, todas as correções tem opção de desfazer. #CONFIA
	%linha%
echo 	Desenvolvido por @LEVIsolution
echo 	Feito de técnico para técnico e para uso técnico. 
echo 	Suporte: Levisolutionoficial@gmail.com
	%linha%
	timeout /t 2 >nul